
### Login de usuario
POST http://localhost:3000/text/create
Content-Type: application/json

{
  "content": "JODER",
  "type": "text",
  "difficulty": "easy",
  "numWords": 50,
  "language": "normal"
}

### Obtener un texto con parámetros
GET http://localhost:3000/text/get?type=normal&numWords=10&difficulty=easy&language=normal